Pages/Error.cshtml.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;

namespace testmvc.Pages
{
    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    [IgnoreAntiforgeryToken]
    public class ErrorModel : PageModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

        private readonly ILogger<ErrorModel> _logger;

        public ErrorModel(ILogger<ErrorModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
            RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
        }
    }
}

Pages/Index.cshtml.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.Extensions.Logging;
using testmvc.Models;

namespace testmvc.Pages
{
    public class IndexModel : PageModel
    {
        public List<SelectListItem> Items => 
        Enumerable.Range(1, 20).Select(x => new SelectListItem {
            Value = x.ToString(),
            Text = x.ToString()
        }).ToList();

        [BindProperty]
        [DisplayName("Age")]
        public int Age { get; set; }

        [BindProperty]
        [DisplayName("First Name")]
        [Required(ErrorMessage = "First Name is required.")]
        public string firstName { get; set; }

        [BindProperty]
        [DisplayName("Last Name")]
        public string lastName { get; set; }

        [BindProperty]
        [DisplayName("Address")]
        public string address { get; set; }

        [BindProperty]
        [DisplayName("City")]
        public string city { get; set; }

        [BindProperty]
        [DisplayName("State")]
        public string state { get; set; }

        [BindProperty]
        [DisplayName("Zip Code")]
        public string zipcode { get; set; }

        [BindProperty]
        [RegularExpression("^[_A-Za-z'`+-.]+([_A-Za-z0-9'+-.]+)*@([A-Za-z0-9-])+(\\.[A-Za-z0-9]+)*(\\.([A-Za-z]*){3,})$",ErrorMessage="Invalid Email Address.")]
        [DisplayName("EMail")]
        [Required(ErrorMessage = "Email Address is required.")]
        [EmailAddress(ErrorMessage="Invalid Email Address.")]
        public string email { get; set; }
        
        public string Message { get; set; } = "Initial Request";
        private readonly ILogger<IndexModel> _logger;

        public IndexModel(ILogger<IndexModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
            _logger.LogInformation("OnGet started!!");
        }

        public IActionResult OnPost()
        {
            _logger.LogInformation("OnPost started!!");
            this.Message = "OnPost started!!";
            _logger.LogInformation(Age.ToString());
            return Page();
        }

        public void OnPostView(int id)
        {
            _logger.LogInformation("OnPostView started!!");
            _logger.LogInformation(Age.ToString());
            this.Message = $"OnPostView fired for {id}";
        }

        public void OnPostFirstSubmit()
        {
            _logger.LogInformation("FirstSubmit Triggered!!");
            this.Message = "FirstSubmit Triggered!!";
        }

        public void OnPostSecondSubmit()
        {
            _logger.LogInformation("SecondSubmit Triggered!!");
            this.Message = "SecondSubmit Triggered!!";
        }
    }
}

Pages/Privacy.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;

namespace testmvc.Pages
{
    public class PrivacyModel : PageModel
    {
        private readonly ILogger<PrivacyModel> _logger;

        public PrivacyModel(ILogger<PrivacyModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
        }
    }
}

Pages/Index.cshtml
@page "{handler?}" 
@model IndexModel
@{
    ViewData["Title"] = "Home page";
}

<div class="text-center">
    <h1 class="display-4">Welcome Everyone!!</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>
<!--<div class="col-lg-1">
    <form method="post" target="_self">
        <button class="btn btn-default">Submit</button>
    </form>
</div>
<div class="col-lg-1">
        <form asp-page-handler="view" asp-route-id="4" method="post">
            <button class="btn btn-default">View</button>
        </form>
</div>-->

@using (Html.BeginForm(FormMethod.Post))
{
    <div class="form-page row">
        <label class="col-sm-2 col-form-label">@Html.LabelFor(m => m.firstName)</label>
        <div class="col-sm-10">@Html.TextBoxFor(m => m.firstName, htmlAttributes: new{@class = "form-control textbx"})
            <span>@Html.ValidationMessageFor(m => m.firstName, "", new {@class = "text-validation"})</span>
        </div>
        
    </div>
    <div class="form-page row">
        <label class="col-sm-2 col-form-label">@Html.LabelFor(m => m.lastName)</label>
        <div class="col-sm-10">@Html.TextBoxFor(m => m.lastName, htmlAttributes: new{@class = "form-control textbx"})</div>
    </div>
    <div class="form-page row">
        <label class="col-sm-2 col-form-label">@Html.LabelFor(m => m.address)</label>
        <div class="col-sm-10">@Html.TextBoxFor(m => m.address, htmlAttributes: new{@class = "form-control textbx"})</div>
    </div>
    <div class="form-page row">
        <label class="col-sm-2 col-form-label">@Html.LabelFor(m => m.city)</label>
        <div class="col-sm-10">@Html.TextBoxFor(m => m.city, htmlAttributes: new{@class = "form-control textbx"})</div>
    </div>
    <div class="form-page row">
        <label class="col-sm-2 col-form-label">@Html.LabelFor(m => m.state)</label>
        <div class="col-sm-10">@Html.TextBoxFor(m => m.state, htmlAttributes: new{@class = "form-control textbx"})</div>
    </div>
    <div class="form-page row">
        <label class="col-sm-2 col-form-label">@Html.LabelFor(m => m.zipcode)</label>
        <div class="col-sm-10">@Html.TextBoxFor(m => m.zipcode, htmlAttributes: new{@class = "form-control textbx"})</div>
    </div>
    <div class="form-page row">
        <label class="col-sm-2 col-form-label">@Html.LabelFor(m => m.email)</label>
        <div class="col-sm-10">@Html.TextBoxFor(m => m.email, htmlAttributes: new{@class = "form-control textbx"})
            <span>@Html.ValidationMessageFor(m => m.email, "", new {@class = "text-validation"})</span>
        </div>
    </div>
    <div class="form-page row">
        <label class="col-sm-2 col-form-label">@Html.LabelFor(m => m.Age)</label>
        <div class="col-sm-10">
            <select asp-for="Age" asp-items="Model.Items" class="form-control textbx">
                <option value="">Pick one</option>
            </select>
        </div>
    </div>
    <div class="form-page row">
        <label class="col-sm-2 col-form-label"></label>
        <div class="col-sm-10">
            <input type="submit" value="Check Values" asp-page-handler = "FirstSubmit" class="btn btn-primary textbx">
        </div>
    </div>
<hr>
    <strong>@Html.Label("firstName"):</strong> @Html.DisplayFor(m => m.firstName)<br>
    <strong>@Html.Label("lastName"):</strong> @Html.DisplayFor(m => m.lastName)<br>
    <strong>@Html.Label("address"):</strong> @Html.DisplayFor(m => m.address)<br>
    <strong>@Html.Label("city"):</strong> @Html.DisplayFor(m => m.city)<br>
    <strong>@Html.Label("state"):</strong> @Html.DisplayFor(m => m.state)<br>
    <strong>@Html.Label("zipcode"):</strong> @Html.DisplayFor(m => m.zipcode)<br>
    <strong>@Html.Label("Email"):</strong> @Html.DisplayFor(m => m.email)<br>
    <strong>@Html.Label("Age"):</strong> @Html.DisplayFor(m => m.Age)<br>
    
    <div class="form-page row">
        <label class="col-sm-2 col-form-label"></label>
        <div class="col-sm-10">
            <input type="submit" value="Submit Values" asp-page-handler = "SecondSubmit" class="btn btn-primary textbx">
        </div>
    </div>
}
<br>
<div>
    <h5>@Model.Message</h5>
</div>

Pages/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - testmvc</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-page="/Index">testmvc</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-page="/Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-page="/Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - testmvc - <a asp-area="" asp-page="/Privacy">Privacy</a>
        </div>
    </footer>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>